select *
FROM layoffs_staging2
WHERE INDUSTRY IS NULL OR INDUSTRY = '';

update layoffs_staging2
set INDUSTRY = NULL
WHERE INDUSTRY = '';

SELECT T1.INDUSTRY, T2.INDUSTRY
FROM layoffs_staging2 T1
JOIN layoffs_staging2 T2
ON T1.COMPANY = T2.COMPANY
WHERE(T1.INDUSTRY IS NULL OR T1.INDUSTRY = '') 
AND T2.INDUSTRY IS NOT NULL;

UPDATE LAYOFFS_STAGING2 T1
JOIN layoffs_staging2 T2
ON T1.COMPANY = T2.COMPANY
SET T1.INDUSTRY = T2.INDUSTRY
WHERE T1.INDUSTRY IS NULL
AND T2.INDUSTRY IS NOT NULL; 
